/* 
 * Copyright (C) 2003-2009 Olivier Boudeville
 *
 * This file is part of the Ceylan library.
 *
 * The Ceylan library is free software: you can redistribute it and/or modify
 * it under the terms of either the GNU Lesser General Public License or
 * the GNU General Public License, as they are published by the Free Software
 * Foundation, either version 3 of these Licenses, or (at your option) 
 * any later version.
 *
 * The Ceylan library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License and the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License and the GNU General Public License along with the Ceylan library.
 * If not, see <http://www.gnu.org/licenses/>.
 *
 * Author: Olivier Boudeville (olivier.boudeville@esperide.com)
 *
 */


#ifndef _SRC_CODE_CEYLANCONFIG_FOR_WINDOWS_H
#define _SRC_CODE_CEYLANCONFIG_FOR_WINDOWS_H 1
 
/* src/code/CeylanConfig.h. Generated automatically at end of configure. */
/* src/code/CeylanTemporaryConfig.h.  Generated by configure.  */
/* src/code/CeylanTemporaryConfig.h.in.  Generated from configure.ac by autoheader.  */

/* Unless specified otherwise, all those preprocessor symbols should */
/* be tested with #ifdef (not #if) */


/* Windows specific section */

/* Define the maximum number of sockets supported */
/* see http://msdn.microsoft.com/library/default.asp?url=/library/en-us/winsock/winsock/porting_socket_applications_to_winsock.asp */
#define FD_SETSIZE 128

/* For faster Builds and Smaller Header Files */
/* (beware to compile errors that it might generate ) */
#define VC_EXTRALEAN
#define WIN32_LEAN_AND_MEAN



/* Version section */


/* Version number of package */
#ifndef CEYLAN_VERSION 
#define CEYLAN_VERSION  "0.7" 
#endif


/* Current Libtool version for the Ceylan library */
#ifndef CEYLAN_LIBTOOL_VERSION 
#define CEYLAN_LIBTOOL_VERSION  "0.7.0" 
#endif

/* Define to the full name and version of this package. */
#ifndef CEYLAN_PACKAGE_STRING 
#define CEYLAN_PACKAGE_STRING  "Ceylan 0.7" 
#endif

/* Define to the version of this package. */
#ifndef CEYLAN_PACKAGE_VERSION 
#define CEYLAN_PACKAGE_VERSION  "0.7" 
#endif



/* General section */

/* 
/* Define to 1 if the target platform is FreeBSD */
#ifndef CEYLAN_ARCH_FREEBSD 
#define CEYLAN_ARCH_FREEBSD  0 
#endif

/* Define to 1 if the target platform is GNU/Linux */
#ifndef CEYLAN_ARCH_LINUX 
#define CEYLAN_ARCH_LINUX  0
#endif

/* Define to 1 if the target platform is NetBSD */
#ifndef CEYLAN_ARCH_NETBSD 
#define CEYLAN_ARCH_NETBSD  0 
#endif

/* Define to 1 if the target platform is OpenBSD */
#ifndef CEYLAN_ARCH_OPENBSD 
#define CEYLAN_ARCH_OPENBSD  0 
#endif

/* Define to 1 if the target platform is a BSD one */
#if CEYLAN_ARCH_FREEBSD ||  CEYLAN_ARCH_NETBSD || CEYLAN_ARCH_OPENBSD
#define CEYLAN_ARCH_BSD 1
#endif

// By default, not BSD :
#ifndef CEYLAN_ARCH_BSD 
#define CEYLAN_ARCH_BSD  0 
#endif


/* Define to 1 if the target platform is a UNIX one */
#if CEYLAN_ARCH_BSD || CEYLAN_ARCH_LINUX
#define CEYLAN_ARCH_UNIX 1
#endif

// By default, not UNIX :
#ifndef CEYLAN_ARCH_UNIX 
#define CEYLAN_ARCH_UNIX  0 
#endif

/* Define to 1 if the target platform is a Windows one */
#ifndef CEYLAN_ARCH_WINDOWS 
#define CEYLAN_ARCH_WINDOWS  1 
#endif

// By default, not UNIX :
#ifndef CEYLAN_ARCH_UNIX 
#define CEYLAN_ARCH_UNIX  0 
#endif

/* Define to 1 if the `closedir' function returns void instead of `int'. */
/* #undef CEYLAN_CLOSEDIR_VOID */

/* Define to 1 if generic debug mode is to be enabled */
#ifndef CEYLAN_DEBUG 
#define CEYLAN_DEBUG  1
#endif

/* Define to 1 if debug mode for name mangling is to be enabled */
#ifndef CEYLAN_DEBUG_DEMANGLE 
#define CEYLAN_DEBUG_DEMANGLE  1
#endif

/* Define to 1 if debug mode for events is to be enabled */
#ifndef CEYLAN_DEBUG_EVENTS 
#define CEYLAN_DEBUG_EVENTS  0
#endif

/* Define to 1 if debug mode for log system is to be enabled */
#ifndef CEYLAN_DEBUG_LOG 
#define CEYLAN_DEBUG_LOG  0
#endif

/* Define to 1 if debug mode for low-level streams is to be enabled */
#ifndef CEYLAN_DEBUG_LOW_LEVEL_STREAMS 
#define CEYLAN_DEBUG_LOW_LEVEL_STREAMS  1 
#endif

/* Define to 1 if debug mode for marshallers is to be enabled */
#ifndef CEYLAN_DEBUG_MARSHALLERS 
#define CEYLAN_DEBUG_MARSHALLERS  1 
#endif

/* Define to 1 if debug mode for network clients is to be enabled */
#ifndef CEYLAN_DEBUG_NETWORK_CLIENTS 
#define CEYLAN_DEBUG_NETWORK_CLIENTS  1 
#endif

/* Define to 1 if debug mode for network servers is to be enabled */
#ifndef CEYLAN_DEBUG_NETWORK_SERVERS 
#define CEYLAN_DEBUG_NETWORK_SERVERS  1 
#endif

/* Define to 1 if debug mode for protocol servers is to be enabled */
#ifndef CEYLAN_DEBUG_PROTOCOL_SERVERS 
#define CEYLAN_DEBUG_PROTOCOL_SERVERS  1 
#endif

/* Define to 1 if debug mode for system layer is to be enabled */
#ifndef CEYLAN_DEBUG_SYSTEM 
#define CEYLAN_DEBUG_SYSTEM  1 
#endif

/* Define to 1 if debug mode for threads is to be enabled */
#ifndef CEYLAN_DEBUG_THREADS 
#define CEYLAN_DEBUG_THREADS  1
#endif

/* Define to 1 if you have the `abs' function. */
#ifndef CEYLAN_USES_ABS 
#define CEYLAN_USES_ABS  1 
#endif

/* Define to 1 if you have the <arpa/inet.h> header file. */
/* #undef CEYLAN_USES_ARPA_INET_H */

/* Define to 1 if you have the <byteswap.h> header file. */
/* #undef CEYLAN_USES_BYTESWAP_H */

/* Define to 1 if you have the `bzero' function. */
#ifndef CEYLAN_USES_BZERO 
#define CEYLAN_USES_BZERO  1 
#endif

/* Define to 1 if you have the <conio.h> header file. */
#ifndef CEYLAN_USES_CONIO_H 
#define CEYLAN_USES_CONIO_H  1 
#endif

/* Define to 1 if you have the `ctime' function. */
#ifndef CEYLAN_USES_CTIME 
#define CEYLAN_USES_CTIME  1 
#endif

/* Define to 1 if you have the declaration of `O_APPEND', and to 0 if you
   don't. */
#ifndef CEYLAN_USES_DECL_O_APPEND 
#define CEYLAN_USES_DECL_O_APPEND  1 
#endif

/* Define to 1 if you have the declaration of `O_CREAT', and to 0 if you
   don't. */
#ifndef CEYLAN_USES_DECL_O_CREAT 
#define CEYLAN_USES_DECL_O_CREAT  1 
#endif

/* Define to 1 if you have the declaration of `O_EXCL', and to 0 if you don't.
   */
#ifndef CEYLAN_USES_DECL_O_EXCL 
#define CEYLAN_USES_DECL_O_EXCL  1 
#endif

/* Define to 1 if you have the declaration of `O_NONBLOCK', and to 0 if you
   don't. */
#ifndef CEYLAN_USES_DECL_O_NONBLOCK 
#define CEYLAN_USES_DECL_O_NONBLOCK  1 
#endif

/* Define to 1 if you have the declaration of `O_RDONLY', and to 0 if you
   don't. */
#ifndef CEYLAN_USES_DECL_O_RDONLY 
#define CEYLAN_USES_DECL_O_RDONLY  1 
#endif

/* Define to 1 if you have the declaration of `O_RDWR', and to 0 if you don't.
   */
#ifndef CEYLAN_USES_DECL_O_RDWR 
#define CEYLAN_USES_DECL_O_RDWR  1 
#endif

/* Define to 1 if you have the declaration of `O_SYNC', and to 0 if you don't.
   */
#ifndef CEYLAN_USES_DECL_O_SYNC 
#define CEYLAN_USES_DECL_O_SYNC  1 
#endif

/* Define to 1 if you have the declaration of `O_TRUNC', and to 0 if you
   don't. */
#ifndef CEYLAN_USES_DECL_O_TRUNC 
#define CEYLAN_USES_DECL_O_TRUNC  1 
#endif

/* Define to 1 if you have the declaration of `O_WRONLY', and to 0 if you
   don't. */
#ifndef CEYLAN_USES_DECL_O_WRONLY 
#define CEYLAN_USES_DECL_O_WRONLY  1 
#endif

/* Define to 1 if you have the declaration of `S_IRGRP', and to 0 if you
   don't. */
#ifndef CEYLAN_USES_DECL_S_IRGRP 
#define CEYLAN_USES_DECL_S_IRGRP  1 
#endif

/* Define to 1 if you have the declaration of `S_IROTH', and to 0 if you
   don't. */
#ifndef CEYLAN_USES_DECL_S_IROTH 
#define CEYLAN_USES_DECL_S_IROTH  1 
#endif

/* Define to 1 if you have the <dirent.h> header file, and it defines `DIR'. */
/* #undef CEYLAN_USES_DIRENT_H */

/* Define to 1 if you have the <direct.h> header file. */
#ifndef CEYLAN_USES_DIRECT_H 
#define CEYLAN_USES_DIRECT_H  1 
#endif

/* Define to 1 if you have the <dlfcn.h> header file. */
#ifndef CEYLAN_USES_DLFCN_H 
#define CEYLAN_USES_DLFCN_H  1 
#endif

/* Define to 1 if you have the `dup' function. */
#ifndef CEYLAN_USES_DUP 
#define CEYLAN_USES_DUP  1 
#endif

/* Define to 1 if you have the `dup2' function. */
#ifndef CEYLAN_USES_DUP2 
#define CEYLAN_USES_DUP2  1 
#endif

/* Define to 1 if you have the <errno.h> header file. */
#ifndef CEYLAN_USES_ERRNO_H 
#define CEYLAN_USES_ERRNO_H  1 
#endif

/* Define to 1 if you have the `execvp' function. */
#ifndef CEYLAN_USES_EXECVP 
#define CEYLAN_USES_EXECVP  1 
#endif

/* Define to 1 if you have the `exit' function. */
#ifndef CEYLAN_USES_EXIT 
#define CEYLAN_USES_EXIT  1 
#endif

/* Define to 1 if you have the `fcntl' function. */
#ifndef CEYLAN_USES_FCNTL 
#define CEYLAN_USES_FCNTL  1 
#endif

/* Define to 1 if you have the <fcntl.h> header file. */
#ifndef CEYLAN_USES_FCNTL_H 
#define CEYLAN_USES_FCNTL_H  1 
#endif

/* Define to 1 if you have the `fork' function. */
/* #undef CEYLAN_USES_FORK */

/* Define to 1 if you have the `getcwd' function. */
/* #undef CEYLAN_USES_GETCWD */

/* Define to 1 if you have the `getdomainname' function. */
/* #undef CEYLAN_USES_GETDOMAINNAME */

/* Define to 1 if you have the `getenv' function. */
/* #undef CEYLAN_USES_GETENV */


/* Define to 1 if you have the `geteuid' function. */
#ifndef CEYLAN_USES_GETEUID 
#define CEYLAN_USES_GETEUID  1 
#endif

/* Define to 1 if you have the `gethostbyaddr' function. */
#ifndef CEYLAN_USES_GETHOSTBYADDR 
#define CEYLAN_USES_GETHOSTBYADDR  1 
#endif

/* Define to 1 if you have the `gethostbyname' function. */
/* #undef CEYLAN_USES_GETHOSTBYNAME */

/* Define to 1 if you have the `gethostname' function. */
/* #undef CEYLAN_USES_GETHOSTNAME */

/* Define to 1 if you have the `getpid' function. */
/* #undef CEYLAN_USES_GETPID */

/* Define to 1 if you have the `getpwuid' function. */
/* #undef CEYLAN_USES_GETPWUID */

/* Define to 1 if you have the `gettimeofday' function. */
/* #undef CEYLAN_USES_GETTIMEOFDAY */

/* Define to 1 if you have the <inttypes.h> header file. */
#ifndef CEYLAN_USES_INTTYPES_H 
#define CEYLAN_USES_INTTYPES_H  1 
#endif

/* Define to 1 if you have the `isdigit' function. */
#ifndef CEYLAN_USES_ISDIGIT 
#define CEYLAN_USES_ISDIGIT  1 
#endif

/* Define to 1 if you have the `islower' function. */
#ifndef CEYLAN_USES_ISLOWER 
#define CEYLAN_USES_ISLOWER  1 
#endif

/* Define to 1 if you have the `isupper' function. */
#ifndef CEYLAN_USES_ISUPPER 
#define CEYLAN_USES_ISUPPER  1 
#endif

/* Define to 1 if you have the `kill' function. */
#ifndef CEYLAN_USES_KILL 
#define CEYLAN_USES_KILL  1 
#endif

/* Define to 1 if you have the `labs' function. */
#ifndef CEYLAN_USES_LABS 
#define CEYLAN_USES_LABS  1 
#endif

/* Define to 1 if you have the <limits.h> header file. */
#ifndef CEYLAN_USES_LIMITS_H 
#define CEYLAN_USES_LIMITS_H  1 
#endif

/* Define to 1 if you have the `llabs' function. */
#ifndef CEYLAN_USES_LLABS 
#define CEYLAN_USES_LLABS  1 
#endif

/* Define to 1 if you have the `localtime' function. */
#ifndef CEYLAN_USES_LOCALTIME 
#define CEYLAN_USES_LOCALTIME  1 
#endif

/* Define to 1 if you have the <ltdl.h> header file. */
/* #undef CEYLAN_USES_LTDL_H */

/* Define to 1 if you have the <machine/bswap.h> header file. */
/* #undef CEYLAN_USES_MACHINE_BSWAP_H */

/* Define to 1 if you have the <math.h> header file. */
#ifndef CEYLAN_USES_MATH_H 
#define CEYLAN_USES_MATH_H  1 
#endif

/* Define to 1 if you have the `memcpy' function. */
#ifndef CEYLAN_USES_MEMCPY 
#define CEYLAN_USES_MEMCPY  1 
#endif

/* Define to 1 if you have the <memory.h> header file. */
#ifndef CEYLAN_USES_MEMORY_H 
#define CEYLAN_USES_MEMORY_H  1 
#endif

/* Define to 1 if you have the `memset' function. */
#ifndef CEYLAN_USES_MEMSET 
#define CEYLAN_USES_MEMSET  1 
#endif

/* Define to 1 if you have the `mkdir' function. */
#ifndef CEYLAN_USES_MKDIR 
#define CEYLAN_USES_MKDIR  1 
#endif

/* Define to 1 if mkdir takes two arguments. */
/* #undef CEYLAN_USES_MKDIR_TWO_ARGS */

/* Define to 1 if you have the <ndir.h> header file, and it defines `DIR'. */
/* #undef CEYLAN_USES_NDIR_H */

/* Define to 1 if you have the <netdb.h> header file, and it defines `DIR'. */
/* #undef CEYLAN_USES_NETDB_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
/* #undef CEYLAN_USES_NETINET_IN_H */

/* Define to 1 if you have the `pipe' function. */
#ifndef CEYLAN_USES_PIPE 
#define CEYLAN_USES_PIPE  1 
#endif

/* Define to 1 if you have the <process.h> header file. */
#ifndef CEYLAN_USES_PROCESS_H 
#define CEYLAN_USES_PROCESS_H  1 
#endif

/* Define to 1 if you have the `pthread_cond_broadcast' function. */
//#ifndef CEYLAN_USES_PTHREAD_COND_BROADCAST 
//#define CEYLAN_USES_PTHREAD_COND_BROADCAST  1 
//#endif

/* Define to 1 if you have the `pthread_cond_destroy' function. */
//#ifndef CEYLAN_USES_PTHREAD_COND_DESTROY 
//#define CEYLAN_USES_PTHREAD_COND_DESTROY  1 
//#endif

/* Define to 1 if you have the `pthread_cond_signal' function. */
//#ifndef CEYLAN_USES_PTHREAD_COND_SIGNAL 
//#define CEYLAN_USES_PTHREAD_COND_SIGNAL  1 
//#endif

/* Define to 1 if you have the `pthread_cond_timedwait' function. */
//#ifndef CEYLAN_USES_PTHREAD_COND_TIMEDWAIT 
//#define CEYLAN_USES_PTHREAD_COND_TIMEDWAIT  1 
//#endif

/* Define to 1 if you have the `pthread_create' function. */
//#ifndef CEYLAN_USES_PTHREAD_CREATE 
//#define CEYLAN_USES_PTHREAD_CREATE  1 
//#endif

/* Define to 1 if you have the <pthread.h> header file. */
//#ifndef CEYLAN_USES_PTHREAD_H 
//#define CEYLAN_USES_PTHREAD_H  1 
//#endif

/* Define to 1 if you have the `pthread_mutex_init' function. */
//#ifndef CEYLAN_USES_PTHREAD_MUTEX_INIT 
//#define CEYLAN_USES_PTHREAD_MUTEX_INIT  1 
//#endif

/* Define to 1 if you have the `pthread_mutex_lock' function. */
//#ifndef CEYLAN_USES_PTHREAD_MUTEX_LOCK 
//#define CEYLAN_USES_PTHREAD_MUTEX_LOCK  1 
//#endif

/* Define to 1 if you have the `pthread_mutex_unlock' function. */
//#ifndef CEYLAN_USES_PTHREAD_MUTEX_UNLOCK 
//#define CEYLAN_USES_PTHREAD_MUTEX_UNLOCK  1 
//#endif

/* Define to 1 if you have the `putenv' function. */
/* #undef CEYLAN_USES_PUTENV */

/* Define to 1 if you have the <pwd.h> header file. */
/* #undef CEYLAN_USES_PWD_H */

/* Define to 1 if you have the `raise' function. */
#ifndef CEYLAN_USES_RAISE 
#define CEYLAN_USES_RAISE  1 
#endif

/* Define to 1 if you have the `regcomp' function. */
/* #undef CEYLAN_USES_REGCOMP */

/* Define to 1 if you have the `regexec' function. */
/* #undef CEYLAN_USES_REGEXEC */

/* Define to 1 if you have the <regex.h> header file. */
/* #undef CEYLAN_USES_REGEX_H */

/* Define to 1 if you have the `regfree' function. */
/* #undef CEYLAN_USES_REGFREE */

/* Define to 1 if you have the `rename' function. */
#ifndef CEYLAN_USES_RENAME 
#define CEYLAN_USES_RENAME  1 
#endif

/* Define to 1 if you have the `rmdir' function. */
/* #undef CEYLAN_USES_RMDIR */

/* Define to 1 if you have the `round' function. */
/* #undef CEYLAN_USES_ROUND */

/* Define to 1 if you have the `roundf' function. */
/* #undef CEYLAN_USES_ROUNDF */

/* Define to 1 if you have the `roundl' function. */
/* #undef CEYLAN_USES_ROUNDL */

/* Define to 1 if you have the `setdomainname' function. */
/* #undef CEYLAN_USES_SETDOMAINNAME */

/* Define to 1 if you have the `setenv' function. */
#ifndef CEYLAN_USES_SETENV 
#define CEYLAN_USES_SETENV  1 
#endif

/* Define to 1 if you have the `sethostname' function. */
/* #undef CEYLAN_USES_SETHOSTNAME */

/* Define to 1 if you have the `signal' function. */
#ifndef CEYLAN_USES_SIGNAL 
#define CEYLAN_USES_SIGNAL  1 
#endif

/* Define to 1 if you have the <signal.h> header file. */
#ifndef CEYLAN_USES_SIGNAL_H 
#define CEYLAN_USES_SIGNAL_H  1 
#endif

/* Define to 1 if you have the `sleep' function. */
/* #undef CEYLAN_USES_SLEEP */

/* Define to 1 if you have the `socket' function. */
/* #undef CEYLAN_USES_SOCKET */

/* Define to 1 if you have the `stat' function. */
/* #undef CEYLAN_USES_STAT */

/* Define to 1 if `stat' has the bug that it succeeds when given the
   zero-length file name argument. */
/* #undef CEYLAN_USES_STAT_EMPTY_STRING_BUG */

/* Define to 1 if stdbool.h conforms to C99. */
#ifndef CEYLAN_USES_STDBOOL_H 
#define CEYLAN_USES_STDBOOL_H  1 
#endif

/* Define to 1 if you have the <stdint.h> header file. */
#ifndef CEYLAN_USES_STDINT_H 
#define CEYLAN_USES_STDINT_H  1 
#endif

/* Define to 1 if you have the <stdlib.h> header file. */
#ifndef CEYLAN_USES_STDLIB_H 
#define CEYLAN_USES_STDLIB_H  1 
#endif

/* Define to 1 if you have the `strdup' function. */
#ifndef CEYLAN_USES_STRDUP 
#define CEYLAN_USES_STRDUP  1 
#endif

/* Define to 1 if you have the `strerror' function. */
#ifndef CEYLAN_USES_STRERROR 
#define CEYLAN_USES_STRERROR  1 
#endif

/* Define to 1 if you have the <strings.h> header file. */
/* #undef CEYLAN_USES_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#ifndef CEYLAN_USES_STRING_H 
#define CEYLAN_USES_STRING_H  1 
#endif

/* Define to 1 if you have the `symlink' function. */
/* #undef CEYLAN_USES_SYMLINK */

/* Define to 1 if you have the `sysinfo' function. */
/* #undef CEYLAN_USES_SYSINFO */

/* Define to 1 if you have the <sys/dir.h> header file, and it defines `DIR'.
   */
/* #undef CEYLAN_USES_SYS_DIR_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
/* #undef CEYLAN_USES_SYS_IOCTL_H */

/* Define to 1 if you have the <sys/ndir.h> header file, and it defines `DIR'.
   */
/* #undef CEYLAN_USES_SYS_NDIR_H */

/* Define to 1 if you have the <sys/select.h> header file. */
/* #undef CEYLAN_USES_SYS_SELECT_H */

/* Define to 1 if you have the <sys/socket.h> header file. */
/* #undef CEYLAN_USES_SYS_SOCKET_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#ifndef CEYLAN_USES_SYS_STAT_H 
#define CEYLAN_USES_SYS_STAT_H  1 
#endif

/* Define to 1 if you have the <sys/sysinfo.h> header file. */
/* #undef CEYLAN_USES_SYS_SYSINFO_H */

/* Define to 1 if you have the <sys/times.h> header file. */
/* #undef CEYLAN_USES_SYS_TIMES_H */

/* Define to 1 if you have the <sys/time.h> header file. */
/* #undef CEYLAN_USES_SYS_TIME_H */

/* Define to 1 if you have the <sys/timeb.h> header file. */
#ifndef CEYLAN_USES_SYS_TIMEB_H 
#define CEYLAN_USES_SYS_TIMEB_H  1 
#endif

/* Define to 1 if you have the <sys/types.h> header file. */
#ifndef CEYLAN_USES_SYS_TYPES_H 
#define CEYLAN_USES_SYS_TYPES_H  1 
#endif

/* Define to 1 if you have the <sys/utime.h> header file. */
#ifndef CEYLAN_USES_SYS_UTIME_H 
#define CEYLAN_USES_SYS_UTIME_H  1 
#endif

/* Define to 1 if you have the <sys/utsname.h> header file. */
/* #undef CEYLAN_USES_SYS_UTSNAME_H */

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
/* #undef CEYLAN_USES_SYS_WAIT_H */

/* Define to 1 if you have the <termios.h> header file. */
/* #undef CEYLAN_USES_TERMIOS_H */

/* Define to 1 if you have the `time' function. */
#ifndef CEYLAN_USES_TIME 
#define CEYLAN_USES_TIME  1 
#endif

/* Define to 1 if you have the `times' function. */
#ifndef CEYLAN_USES_TIMES 
#define CEYLAN_USES_TIMES  1 
#endif

/* Define to 1 if you have the <time.h> header file. */
#ifndef CEYLAN_USES_TIME_H 
#define CEYLAN_USES_TIME_H  1 
#endif

/* Define to 1 if you have the `uname' function. */
/* #undef CEYLAN_USES_UNAME */

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef CEYLAN_USES_UNISTD_H */

/* Define to 1 if you have the `unlink' function. */
/* #undef CEYLAN_USES_UNLINK */

/* Define to 1 if you have the `unsetenv' function. */
/* #undef CEYLAN_USES_UNSETENV */

/* Define to 1 if you have the `utime' function. */
/* #undef CEYLAN_USES_UTIME */

/* Define to 1 if you have the <utime.h> header file. */
/* #undef CEYLAN_USES_UTIME_H */

/* Define to 1 if `utime(file, NULL)' sets file's timestamp to the present. */
#ifndef CEYLAN_USES_UTIME_NULL 
#define CEYLAN_USES_UTIME_NULL  1 
#endif

/* Define to 1 if you have the `vfork' function. */
#ifndef CEYLAN_USES_VFORK 
#define CEYLAN_USES_VFORK  1 
#endif

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef CEYLAN_USES_VFORK_H */

/* Define to 1 if you have the `waitpid' function. */
/* #undef CEYLAN_USES_WAITPID */

/* Define to 1 if you have the <windows.h> header file (hence the PSDK). */
#ifndef CEYLAN_USES_WINDOWS_H 
#define CEYLAN_USES_WINDOWS_H  1 
#endif

/* Define to 1 if you have the <winsock2.h> header file (hence the PSDK). */
#ifndef CEYLAN_USES_WINSOCK2_H 
#define CEYLAN_USES_WINSOCK2_H  1 
#endif

/* Define to 1 if you have the <ws2tcpip.h> header file (hence the PSDK). */
#ifndef CEYLAN_USES_WS2TCPIP_H 
#define CEYLAN_USES_WS2TCPIP_H  1 
#endif


/* Define to 1 if `fork' works. */
#ifndef CEYLAN_USES_WORKING_FORK 
#define CEYLAN_USES_WORKING_FORK  1 
#endif

/* Define to 1 if `vfork' works. */
#ifndef CEYLAN_USES_WORKING_VFORK 
#define CEYLAN_USES_WORKING_VFORK  1 
#endif


/* Define to 1 if the system has the type `_Bool'. */
#ifndef CEYLAN_USES__BOOL 
#define CEYLAN_USES__BOOL  1 
#endif

/* Define to 1 if you have the `_chdir' function. */
#ifndef CEYLAN_USES__CHDIR 
#define CEYLAN_USES__CHDIR  1 
#endif

/* Define to 1 if you have the `_dupenv_s' function. */
#ifndef CEYLAN_USES__DUPENV_S 
#define CEYLAN_USES__DUPENV_S  1 
#endif

/* Define to 1 if you have the `_ftime_s' function. */
#ifndef CEYLAN_USES__FTIME_S 
#define CEYLAN_USES__FTIME_S  1 
#endif

/* Define to 1 if you have the `_getcwd' function. */
#ifndef CEYLAN_USES__GETCWD
#define CEYLAN_USES__GETCWD  1 
#endif

/* Define to 1 if you have the `_putenv_s' function. */
#ifndef CEYLAN_USES__PUTENV_S
#define CEYLAN_USES__PUTENV_S  1 
#endif

/* Define to 1 if you have the `_mkdir' function. */
#ifndef CEYLAN_USES__MKDIR
#define CEYLAN_USES__MKDIR  1 
#endif

/* Define to 1 if you have the `_rmdir' function. */
#ifndef CEYLAN_USES__RMDIR
#define CEYLAN_USES__RMDIR  1 
#endif

/* Define to 1 if you have the `_stat' function. */
#ifndef CEYLAN_USES__STAT
#define CEYLAN_USES__STAT  1 
#endif

/* Define to 1 if you have the `_unlink' function. */
#ifndef CEYLAN_USES__UNLINK
#define CEYLAN_USES__UNLINK  1 
#endif

/* Define to 1 if you have the `_utime' function. */
#ifndef CEYLAN_USES__UTIME 
#define CEYLAN_USES__UTIME  1 
#endif


/* Define to 1 if `lstat' dereferences a symlink specified with a trailing
   slash. */
#ifndef CEYLAN_LSTAT_FOLLOWS_SLASHED_SYMLINK 
#define CEYLAN_LSTAT_FOLLOWS_SLASHED_SYMLINK  1 
#endif

/* Name of package */
#ifndef CEYLAN_PACKAGE 
#define CEYLAN_PACKAGE  "ceylan" 
#endif

/* Define to the address where bug reports for this package should be sent. */
#ifndef CEYLAN_PACKAGE_BUGREPORT 
#define CEYLAN_PACKAGE_BUGREPORT  "ceylan-bugs@lists.sourceforge.net" 
#endif

/* Define to the full name of this package. */
#ifndef CEYLAN_PACKAGE_NAME 
#define CEYLAN_PACKAGE_NAME  "Ceylan" 
#endif


/* Define to the one symbol short name of this package. */
#ifndef CEYLAN_PACKAGE_TARNAME 
#define CEYLAN_PACKAGE_TARNAME  "ceylan" 
#endif


/* Define as the return type of signal handlers (`int' or `void'). */
#ifndef CEYLAN_RETSIGTYPE 
#define CEYLAN_RETSIGTYPE  void 
#endif

/* Define to 1 if the target platform is little endian */
#ifndef CEYLAN_RUNS_ON_LITTLE_ENDIAN 
#define CEYLAN_RUNS_ON_LITTLE_ENDIAN  1 
#endif

/* Define to the type of arg 1 for `select'. */
#ifndef CEYLAN_SELECT_TYPE_ARG1 
#define CEYLAN_SELECT_TYPE_ARG1  int 
#endif

/* Define to the type of args 2, 3 and 4 for `select'. */
#ifndef CEYLAN_SELECT_TYPE_ARG234 
#define CEYLAN_SELECT_TYPE_ARG234  (fd_set *) 
#endif

/* Define to the type of arg 5 for `select'. */
#ifndef CEYLAN_SELECT_TYPE_ARG5 
#define CEYLAN_SELECT_TYPE_ARG5  (struct timeval *) 
#endif

/* Define to 1 if you have the ANSI C header files. */
#ifndef CEYLAN_STDC_HEADERS 
#define CEYLAN_STDC_HEADERS  1 
#endif

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#ifndef CEYLAN_TIME_WITH_SYS_TIME 
#define CEYLAN_TIME_WITH_SYS_TIME  1 
#endif

/* Define to 1 if your <sys/time.h> declares `struct tm'. */
/* #undef CEYLAN_TM_IN_SYS_TIME */

/* Define to 1 if Ceylan is to provide advanced file attribute support */
#ifndef CEYLAN_USES_ADVANCED_FILE_ATTRIBUTES 
#define CEYLAN_USES_ADVANCED_FILE_ATTRIBUTES  0 
#endif

/* Define to 1 if Ceylan is to support avanced process management */
#ifndef CEYLAN_USES_ADVANCED_PROCESS_MANAGEMENT 
#define CEYLAN_USES_ADVANCED_PROCESS_MANAGEMENT  0 
#endif

/* Define to 1 if fcntl is to be preferred to ioctl */
#ifndef CEYLAN_USES_FCNTL_FOR_NONBLOCKING_SOCKETS 
#define CEYLAN_USES_FCNTL_FOR_NONBLOCKING_SOCKETS  0
#endif

/* Define to 1 if Ceylan is to provide file descriptor support */
#ifndef CEYLAN_USES_FILE_DESCRIPTORS 
#define CEYLAN_USES_FILE_DESCRIPTORS  0 
#endif

/* Define to 1 if Ceylan is to provide file lock support */
#ifndef CEYLAN_USES_FILE_LOCKS 
#define CEYLAN_USES_FILE_LOCKS  0 
#endif

/* Define to 1 if Ceylan is to provide network support */
#ifndef CEYLAN_USES_NETWORK 
#define CEYLAN_USES_NETWORK  1
#endif


/* Define to 1 if Ceylan is to support plugin */
#ifndef CEYLAN_USES_PLUGINS 
#define CEYLAN_USES_PLUGINS  0 
#endif

/* Define to 1 if Ceylan is to use regular expressions internally */
#ifndef CEYLAN_USES_REGEX 
#define CEYLAN_USES_REGEX  0
#endif

/* Define to 1 if Ceylan is to support signals */
#ifndef CEYLAN_USES_SIGNALS 
#define CEYLAN_USES_SIGNALS  0 
#endif

/* Define to 1 if Ceylan is to provide symbolic link support */
#ifndef CEYLAN_USES_SYMBOLIC_LINKS 
#define CEYLAN_USES_SYMBOLIC_LINKS  0 
#endif

/* Define to 1 if Ceylan is to provide multithreading support */
#ifndef CEYLAN_USES_THREADS 
#define CEYLAN_USES_THREADS  0
#endif


/* Define to empty if `const' does not conform to ANSI C. */
/* #undef _ceylan_const */

/* Define to `__inline__' or `__inline' if that's what the C compiler
   calls it, or to nothing if 'inline' is not supported under any name.  */
#ifndef __cplusplus
/* #undef _ceylan_inline */
#endif

/* Define to `int' if <sys/types.h> does not define. */
/* #undef _ceylan_pid_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef _ceylan_size_t */

/* Define as `fork' if `vfork' does not work. */
/* #undef _ceylan_vfork */

/* Define to empty if the keyword `volatile' does not work. Warning: valid
   code using `volatile' can become incorrect without. Disable with care. */
/* #undef _ceylan_volatile */

/* once: _SRC_CODE_CEYLANCONFIG_FOR_WINDOWS_H */
#endif
