WOOPER_TOP = ..


OVERALL_DOCUMENT_TARGET = wooper.rst


doc: wooper.pdf wooper.html


# For COMMON_TOP:
include $(WOOPER_TOP)/GNUmakesettings.inc

# Not used for a better readability: 
#PROJECT_CSS = $(COMMON_TOP)/doc/Ceylan-docutils.css

include $(COMMON_TOP)/doc/GNUmakerules-docutils.inc

