TOP = ../../..

.PHONY:

CPP_FLAGS_COMMON = $(CEYLAN_GENERIC_INC) $(CEYLAN_LOGS_INC) \
	$(CEYLAN_INTERFACES_INC) $(CEYLAN_MATHS_INC) $(CEYLAN_MODULES_INC)  \
	$(CEYLAN_NETWORK_INC)


all: compile


# Small hack that allows to retrieve from autoconf files the relevant targets:
include Makefile.am


ARM7_OBJ_FILES = $(patsubst %.cc,%.arm7.o,$(SYSTEM_IMPLEMENTATIONS))
ARM9_OBJ_FILES = $(patsubst %.cc,%.arm9.o,$(SYSTEM_IMPLEMENTATIONS))


include $(TOP)/src/conf/build/$(CROSS_TARGET)/Makerules.inc
