CEYLAN_ERLANG_TOP = .


MODULES_DIRS = common wooper core

# Defined here to avoid polluting other projects using the Ceylan ruleset:
PROJECT_NAME := Ceylan-Erlang

PROJECT_VERSION := 0.1

OVERALL_DOCUMENT_SOURCE = Ceylan-Erlang-manual.rst


include $(CEYLAN_ERLANG_TOP)/GNUmakerules.inc

