TRACE_TOP = .


.PHONY: release release-zip release-bz2   \
	prepare-release clean-release clean-archive

 
MODULES_DIRS = src doc #conf 



# No trace supervisor or graphical output wanted when running all tests from 
# a root directory (batch mode vs interactive one):	 	
CMD_LINE_OPT = "--batch"

	
include $(TRACE_TOP)/GNUmakesettings.inc

